cassandra:
  image: mashape/cassandra
  expose:
    - "9042"

kong:
  build: .
  expose:
    - "8000"
    - "8001"
  environment:
    CASSANDRA_HOSTNAME: cassandra
    CASSANDRA_PORT: 9042
  links:
    - cassandra
